# Generated by Django 5.1.2 on 2024-10-26 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvapp', '0002_alter_supplier_phone_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouseentry',
            name='products',
        ),
        migrations.RemoveField(
            model_name='warehouseexit',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='warehouseexit',
            name='products',
        ),
        migrations.RemoveField(
            model_name='warehouseexit',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='warehouseexit',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='csvapp.supplier'),
        ),
        migrations.AlterField(
            model_name='entryproduct',
            name='warehouse_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_products', to='csvapp.warehouseentry'),
        ),
        migrations.AlterField(
            model_name='exitproduct',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='exitproduct',
            name='warehouse_exit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_products', to='csvapp.warehouseexit'),
        ),
        migrations.AlterField(
            model_name='warehouseentry',
            name='total_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='warehouseexit',
            name='exit_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='warehouseexit',
            name='total_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
