# Generated by Django 5.1.2 on 2024-11-09 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvapp', '0003_remove_warehouseentry_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='csvapp.supplier'),
        ),
        migrations.AlterField(
            model_name='warehouseexit',
            name='exit_date',
            field=models.DateField(),
        ),
    ]
