# Generated by Django 5.1.2 on 2024-11-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvapp', '0004_alter_product_supplier_alter_warehouseexit_exit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseentry',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chưa nhập'), ('PROCESSING', 'Đang xử lý'), ('COMPLETED', 'Đã nhập')], default='PENDING', max_length=10),
        ),
    ]
