# Generated by Django 5.1.2 on 2024-11-23 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csvapp', '0007_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
